### ISSUE TITLE
Getting "error: missing required module 'Alamofire'" when trying to build

### ISSUE THREAD

**Issue by jonsteinmetz** [bustoutsolutions/siesta#12] opened 2015-11-24 16:15 UTC
I have done a clean and a clean build directory which does not help.If I add 
```
github "Alamofire/Alamofire" "3.1.2"
```
to my Cartfile then things seem to build and run. Is this as intended?

Thanks

**Comment by pcantrell** [comment] 2015-11-24 16:28
It’s supposed to work without Alamofire, but I’m getting reports of the same error as you with the latest beta.

I’ve had trouble pinning it down, but my current best guess is that optional framework dependencies simply don’t allow third-party frameworks to be optional, and it’s only working for some people because Alamofire is present in their Xcode temp directory.

Keep using your current workaround, and I hope to have a new beta out soon to resolve this.

**Comment by jonsteinmetz** [comment] 2015-11-24 19:50
Hey Paul, thanks. Let me know if there is any further information I can provide.

**Comment by pcantrell** [comment] 2015-11-24 19:53
Could give master a try and see if it fixes your problem?

(Probably best to scrub your `Carthage` and xcode temp dirs just to be sure.)

**Comment by pcantrell** [comment] 2015-11-25 18:53
Fix confirmed by Jon via email. Will be released in next beta.

**Closed by pcantrell** 2015-11-25 18:53 UTC
