### ISSUE TITLE
ResourceStatusOverlay is broken on rc.1

### ISSUE THREAD

**Issue by kl** [bustoutsolutions/siesta#120] opened 2016-10-03 14:07 UTC
Hi,

I'm using the ResourceStatusOverlay class and it works fine with Siesta 1.0-rc.0 but it appears to have broken with rc.1

Here is part of my code:

```swift
// stage is a view controller that embeds the overlay
stage.overlayResources = [api.gists]
api.gists.loadIfNeeded()
```
```swift
// from the stage class

  var overlayResources: [Resource] = [] {
    didSet {
      oldValue.forEach { $0.removeObservers(ownedBy: overlay) }
      overlayResources.forEach { $0.addObserver(overlay) }
    }
  }

  override func viewDidLoad() {
    super.viewDidLoad()
    embedOverlay()
    afterLoad?()
    afterLoad = nil
  }
  
  private func embedOverlay() {
    overlay.embedIn(self)
    overlay.backgroundColor = overlay.backgroundColor?.withAlphaComponent(0.5)
  }
```
So this shows the overlay correctly on rc.0 but on rc.1 the overlay is not shown after the call to ```api.gists.loadIfNeeded()```

Also if I change the order of the calls to
```swift
api.gists.loadIfNeeded()
stage.overlayResources = [api.gists]
```
The overlay _is_ shown in rc.1, but it never disappears, even though the request completes.

**Comment by pcantrell** [comment] 2016-10-03 16:13
Curious. Your code certainly looks good. This may be a bug introduced by the performance tuning in rc.1.

What output do you get with `LogCategory.enabled = [.stateChanges, .observers]`?

Any chance you can create a self-contained example class/project that reproduces the issue? I realize that’s a tall order since you won’t want to expose your API, but if you can, I’ll point the debugger at it and see what’s happening.

**Comment by kl** [comment] 2016-10-04 13:41
**rc.1**

Load before observe (overlay never removed):

```
Siesta:observers      │ <deallocated: <SiestaUI.ResourceStatusOverlay: 0x7f9b8b51ef70; frame = (0 0; 375 667); hidden = YES; layer = <CALayer: 0x60800023dfe0>>> removing observer whose owners are all gone: <deallocated: <SiestaUI.ResourceStatusOverlay: 0x7f9b8b51ef70; frame = (0 0; 375 667); hidden = YES; layer = <CALayer: 0x60800023dfe0>>>
Siesta:observers      │ Resource(…/gists)[L] sending requested event to 1 observer
Siesta:observers      │   ↳ requested → ClosureObserver(HomeDirector.swift:99)
Siesta:stateChanges   │ Resource(…/gists)[] received new data from network : Entity<Any>(content: [Model.GistEntity(description: "sddfs", isPublic: false, file: Model.GistFileInfo(size: 12, raw_url: "https://gist.githubusercontent.com/kl/494d25fe933ef0459d1f2c9441e91a0d/raw/e5c384274efafef1dd434c4648fbd7901a418f9d/sddfs", filename: "sddfs", language: nil)), Model.GistEntity(…
Siesta:observers      │ Resource(…/gists)[D] sending newData(network) event to 1 observer
Siesta:observers      │   ↳ newData(network) → ClosureObserver(HomeDirector.swift:99)
```
Load after observe (overlay never shown):

```
Siesta:observers      │ Resource(…/gists)[L] sending requested event to 1 observer
Siesta:observers      │   ↳ requested → ClosureObserver(HomeDirector.swift:99)
Siesta:observers      │ <deallocated: <SiestaUI.ResourceStatusOverlay: 0x7faf0942d840; frame = (0 0; 375 667); hidden = YES; layer = <CALayer: 0x60800022f6c0>>> removing observer whose owners are all gone: <deallocated: <SiestaUI.ResourceStatusOverlay: 0x7faf0942d840; frame = (0 0; 375 667); hidden = YES; layer = <CALayer: 0x60800022f6c0>>>
Siesta:stateChanges   │ Resource(…/gists)[] received new data from network : Entity<Any>(content: [Model.GistEntity(description: "sddfs", isPublic: false, file: Model.GistFileInfo(size: 12, raw_url: "https://gist.githubusercontent.com/kl/494d25fe933ef0459d1f2c9441e91a0d/raw/e5c384274efafef1dd434c4648fbd7901a418f9d/sddfs", filename: "sddfs", language: nil)), Model.GistEntity(…
Siesta:observers      │ Resource(…/gists)[D] sending newData(network) event to 1 observer
Siesta:observers      │   ↳ newData(network) → ClosureObserver(HomeDirector.swift:99)
```

**rc.0**

Load before observe:

```
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[L] sending requested to 1 observer
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[L] sending requested to (ClosureObserver in _C44BB9FA2CCB62875EDCC4C65C6D80F6)(closure: (Function))
[Siesta:stateChanges] Siesta.Resource(https://api.github.com/gists)[] received new data from network : Entity<Any>(content: [Model.GistEntity(description: "sddfs", isPublic: false, file: Model.GistFileInfo(size: 12, raw_url: "https://gist.githubusercontent.com/kl/494d25fe933ef0459d1f2c9441e91a0d/raw/e5c384274efafef1dd434c4648fbd7901a418f9d/sddfs", filename: "sddfs", language: nil)), Model.GistEntity(…
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[D] sending newData(network) to 2 observers
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[D] sending newData(network) to (ClosureObserver in _C44BB9FA2CCB62875EDCC4C65C6D80F6)(closure: (Function))
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[D] sending newData(network) to <SiestaUI.ResourceStatusOverlay: 0x7f94d0704520; frame = (0 64; 375 603); layer = <CALayer: 0x60000022ae20>>
```
Load after observe:

```
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[L] sending requested to 2 observers
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[L] sending requested to (ClosureObserver in _C44BB9FA2CCB62875EDCC4C65C6D80F6)(closure: (Function))
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[L] sending requested to <SiestaUI.ResourceStatusOverlay: 0x7f8fc3c2c070; frame = (0 0; 375 667); hidden = YES; layer = <CALayer: 0x60800042ec40>>
[Siesta:stateChanges] Siesta.Resource(https://api.github.com/gists)[] received new data from network : Entity<Any>(content: [Model.GistEntity(description: "sddfs", isPublic: false, file: Model.GistFileInfo(size: 12, raw_url: "https://gist.githubusercontent.com/kl/494d25fe933ef0459d1f2c9441e91a0d/raw/e5c384274efafef1dd434c4648fbd7901a418f9d/sddfs", filename: "sddfs", language: nil)), Model.GistEntity(…
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[D] sending newData(network) to 2 observers
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[D] sending newData(network) to (ClosureObserver in _C44BB9FA2CCB62875EDCC4C65C6D80F6)(closure: (Function))
[Siesta:observers] Siesta.Resource(https://api.github.com/gists)[D] sending newData(network) to <SiestaUI.ResourceStatusOverlay: 0x7f8fc3c2c070; frame = (0 64; 375 603); layer = <CALayer: 0x60800042ec40>>
```

I guess the ```deallocated: <SiestaUI.ResourceStatusOverlay: 0x7faf0942d840``` has something to do with it?

If you need to debug this you can use my app here https://github.com/kl/dehub
You can log in with your Github credentials.

**Comment by pcantrell** [comment] 2016-10-05 03:28
From the logs, it certainly looks as though nothing except Siesta retains `overlay`, and since it’s registered with Siesta as being self-owned, it gets deallocated.

Thanks for sharing the code! I got your project to build (your Cartfile seems to be missing Gloss, BTW?), and got the app running. Cool undertaking.

I’m afraid I wasn’t able to reproduce your issue, though: it seems to work perfectly even after I upgraded Siesta to rc.1: I can log in, see gists, and view individual ones, with the loading indicator working just fine the whole time. I tried both in the simulator and on a device, building with both debug and production configurations. Couldn’t get it to fail.

I wonder if I have the latest code? I investigated where a `ResourceStatusOverlay` might ever be deallocated, and found this:

    class DirectedViewController : UIViewController {
      ...
      let overlay: ResourceStatusOverlay = {
        let o = ResourceStatusOverlay()
        o.displayPriority = [.ManualLoading, .Loading, .Error, .AnyData]
        return o
      }()

…which pretty clearly ties the lifecycle of the overlay to its enclosing VC. Perhaps a recent change made `observer` a computed property or otherwise no longer a `let`, weak, more locally allocated…?

**Comment by kl** [comment] 2016-10-05 07:47
Thanks for taking the time to debug this!  You have the latest code (btw I'm not using Gloss any more and had forgot to remove it from the project  :sweat_smile:). The reason you are seeing the loading indicator is because it works for requests using `trackManualLoad` (for example the login screen). Where it is not working is for resources added to the overlay with `addObserver` (the main gists screen).

If you go to HomeDirector and change this
```swift
  override func stageDidLoad(stage: HomeStage) {
    addApiObservers()
    observe(outputs: stage.outputs)
    stage.overlayResources = [api.gists]
    api.gists.loadIfNeeded()
  }
```

to this:

```swift
  override func stageDidLoad(stage: HomeStage) {
    addApiObservers()
    observe(outputs: stage.outputs)
    api.gists.loadIfNeeded()
    stage.overlayResources = [api.gists]
  }
```

You should trigger the bug where the overlay is never removed that happens on rc.1 but not on rc.0

**Comment by pcantrell** [comment] 2016-10-05 22:47
Well, congratulations, you found a [bug in Swift](https://bugs.swift.org/browse/SR-2867)! It’s a nice sticky one, too.

Please **upvote that bug** to let Apple & the community know we care!

In the meantime, #121 should work around the bug. @kl, I verified it with your project, but would you be willing to double check yourself that the fix works as you expect? Point your Cartfile at the `issue-120` branch, and let me know. I’ll wait to hear from you before I merge.

**Comment by kl** [comment] 2016-10-06 06:57
👍 I can confirm it now works as expected!

**Comment by pcantrell** [comment] 2016-10-06 19:03
Merged to master. Thanks, @kl!

**Closed** 2016-10-06 19:03 UTC
