### ISSUE TITLE
 unexpected duplicate task error for new Xcode  build system from Xcode 10 IOS 12.0.1

### ISSUE THREAD

**Issue by NermeenNery** [bustoutsolutions/siesta#282] opened 2018-10-23 11:16 UTC

**Comment by pcantrell** [comment] 2018-10-23 15:34
This isn’t nearly enough information to diagnose or reproduce the issue. Mozilla’s guidelines are a pretty good reference on writing useful bug reports: https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

I’m closing this assuming it’s duplicate of https://github.com/bustoutsolutions/siesta/issues/242.

**Closed by pcantrell** 2018-10-23 15:34 UTC
