### ISSUE TITLE
Pods/Siesta/Source/Siesta/Support/WeakCache.swift:14:42: Type 'NSNotification.Name' has no member 'UIApplication'

### ISSUE THREAD

**Issue by danysz** [bustoutsolutions/siesta#276] opened 2018-09-23 02:25 UTC
I got this error when I moved to Siesta 1.4.1 with Xcode 10 and Swift 4.2

**Comment by pcantrell** [comment] 2018-09-23 18:54
Duplicate of #275.

**Closed by pcantrell** 2018-09-23 18:54 UTC
